# Based on Microsoft's docker samples for dotnet core
# available at https://github.com/dotnet/dotnet-docker/tree/master/samples/aspnetapp
FROM mcr.microsoft.com/dotnet/sdk:7.0-jammy AS build
# First install nodejs - required to build generated client app
WORKDIR /app
RUN apt-get update -yq && apt-get install -yq curl
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash - && \
    apt-get update && \
    apt-get install -yq nodejs && \
    rm -rf /var/lib/apt/lists/*

# install blazor build tools only if INCLUDE_BLAZOR is set to true
ARG INCLUDE_BLAZOR=false
RUN if [ "$INCLUDE_BLAZOR" = "true" ]; then dotnet tool install -g Microsoft.Web.LibraryManager.Cli ; fi
RUN if [ "$INCLUDE_BLAZOR" = "true" ]; then dotnet tool install -g Excubo.WebCompiler ; fi
ENV PATH="${PATH}:/root/.dotnet/tools"
# Restore dependencies of .net core projects taking advantage of docker layer caching
COPY src/*/*.csproj ./src/
COPY Directory.Packages.props Directory.Packages.props
RUN for file in $(ls src/*.csproj); do mkdir -p ${file%.*} && mv $file ${file%.*}; done
COPY src/client/*/*.csproj ./src/client/
RUN for file in $(ls src/client/*.csproj); do mkdir -p ${file%.*} && mv $file ${file%.*}; done
RUN dotnet restore "src/Jhipster/Jhipster.csproj"

# Copy everything else and build app
COPY . ./
WORKDIR src/Jhipster/
RUN dotnet publish "Jhipster.csproj" -c Release -o /app/out

# Final stage/image
FROM mcr.microsoft.com/dotnet/aspnet:7.0-jammy AS runtime
EXPOSE 80
WORKDIR /app
COPY docker-entrypoint-back.sh .
RUN chmod +x /app/docker-entrypoint-back.sh
COPY --from=build /app/out .
ENV ASPNETCORE_ENVIRONMENT=Production
ARG INCLUDE_BLAZOR
ENV INCLUDE_BLAZOR $INCLUDE_BLAZOR
ENV ServerUrl="https://localhost:8080"

ENTRYPOINT ["./docker-entrypoint-back.sh"]
