version: "2.2"
services:
  jhipster-app:
    build:
      context: ../
      dockerfile: Dockerfile-Back
    ports:
      - 8080:80
  jhipster-front:
    build:
      context: ../
      dockerfile: Dockerfile-Front
      args:
        - ServerUrl=http://localhost:8080
    ports:
      - 8081:80
