version: "3.8"
services:
  jhipster-influxdb:
    # Full tag list: https://hub.docker.com/r/library/influxdb/tags/
    image: docker.io/influxdb:latest
    volumes:
      # Mount for influxdb data directory
      - ./influxdb/data:/var/lib/influxdb
      # Mount for influxdb configuration
      - ./influxdb/config/:/etc/influxdb/
    ports:
      # The API for InfluxDB is served on port 8086
      - "8086:8086"
      - "8082:8082"
      # UDP Port
      - "8089:8089/udp"

  jhipster-telegraf:
    # Full tag list: https://hub.docker.com/r/library/telegraf/tags/
    image: docker.io/telegraf:latest
    environment:
      HOSTNAME: "tick-host"
    # Telegraf requires network access to InfluxDB
    links:
      - jhipster-influxdb
    ports:
      - "8094:8094"
      - "6514:6514"
    volumes:
      # Mount for telegraf configuration
      - ./telegraf/:/etc/telegraf/
      # Mount for Docker API access
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - jhipster-influxdb

  jhipster-grafana:
    image: grafana/grafana:latest
    ports:
      - 3000:3000
    links:
      - jhipster-influxdb:influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
      GF_SECURITY_SECRET_KEY: grafana
      GF_USERS_ALLOW_SIGN_UP: "true"
      GF_USERS_ALLOW_ORG_CREATE: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: grafana
      GF_DASHBOARDS_JSON_ENABLED: "true"
      GF_DASHBOARDS_JSON_PATH: /opt/grafana
    volumes:
      - ./grafana/data/:/var/lib/grafana
      - ./grafana/data/log:/var/log/grafana
      - ./grafana/data/plugins:/var/lib/grafana/plugins
      - ./grafana/data/provisioning:/etc/grafana/provisioning/datasources
      - ./grafana/data/dashboard:/etc/grafana/provisioning/dashboards
    restart: always
    depends_on:
      - jhipster-influxdb
      - jhipster-telegraf
#  jhipster-kapacitor:
#    # Full tag list: https://hub.docker.com/r/library/kapacitor/tags/
#    image: docker.io/kapacitor:latest
#    volumes:
#      # Mount for kapacitor data directory
#      - ./kapacitor/data/:/var/lib/kapacitor
#      # Mount for kapacitor configuration
#      - ./kapacitor/config/:/etc/kapacitor/
#    # Kapacitor requires network access to Influxdb
#    links:
#      - jhipster-influxdb
#    ports:
#      # The API for Kapacitor is served on port 9092
#      - "9092:9092"

#  jhipster-chronograf:
#    # Full tag list: https://hub.docker.com/r/library/chronograf/tags/
#    image: docker.io/chronograf:latest
#    environment:
#      RESOURCES_PATH: "/usr/share/chronograf/resources"
#    volumes:
#      # Mount for chronograf database
#      - ./chronograf/data/:/var/lib/chronograf/
#    links:
#      # Chronograf requires network access to InfluxDB and Kapacitor
#      #      - jhipster-influxdb
#      - jhipster-kapacitor
#    ports:
#      # The WebUI for Chronograf is served on port 8888
#      - "8888:8888"
#    depends_on:
#      - jhipster-kapacitor
#      - jhipster-influxdb
#      - jhipster-telegraf

